// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import { default as openNextWorker } from "./.open-next/worker.js";
import { consumeDocuments } from "./src/workers/queue-consumer";
import type { ExportedHandler, MessageBatch } from "@cloudflare/workers-types";

const worker: ExportedHandler<Env> = {
  fetch: openNextWorker.fetch,
  async queue(batch: MessageBatch<unknown>, env: Env) {
    await consumeDocuments(
      batch as Parameters<typeof consumeDocuments>[0],
      env as Parameters<typeof consumeDocuments>[1],
    );
  },
};

export default worker;
